### ISSUE TITLE
Additional information request

### ISSUE THREAD

**Issue by mncarmic** [epid8060fall2019/ellencheng-introduction#1]
Hi Ellen! My name is Mia Carmichael and your name happened to be under mine in the class list! Your website and background information are extremely interesting! We have some topics of interest in common including, antibiotic resistance, microbiome diversity, and disease transmission between humans and animals. One thing I would like to know more about you is where you grew up/where are you from?

**Comment by ellenmonster** [comment]
Thanks for the suggestion @mncarmic! I've updated my Introduction with the additional information
